commands:

  - type: sync
    repo: https://github.com/copycat-killer/lain
    dst:  '<%= get_var! :"awesome_wm.base_dir", type: :directory %>/lain'
    only: f?awesome_wm

elems:

  - src:  ^(.+)$
    dst:  ~/.config/awesome/<1>
    only: f?awesome_wm


# vim: set filetype=eruby.yaml :
